# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Camron Borders
email: borderce@rose-hulman.edu
description: > # this means to ignore newlines until "baseurl:"
  Base website for playing around with HTML and CSS. Rose-Hulman student. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://camborders.com" # the base hostname & protocol for your site
twitter_username: CamronBorders
github_username:  Borderce

# Build settings
markdown: kramdown
